
name: CICD for QA

on:
  push:
    branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use node js
        uses: actions/setup-node@v1
        with:
         node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm install
          npm run build
        env: 
          CI: true   
          
      # current directory
      - name: find the current directory
        run: |
           pwd
           ls -l
           cd build
           pwd
           ls -l
           
  deploy:
    name: Deploy to EC2 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SOURCE: /home/runner/work/CICD-Youtube/CICD-Youtube/dist
          ARGS: "-rltgoDzvO --delete"
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
          EXCLUDE: "/dist/, /node_modules/"

